- name: Create dirs list
  ansible.builtin.set_fact:
    pdmn_webssh2_dirs: >-
      {{
        pdmn_webssh2_containers 

        | selectattr('volumes', 'defined') 
        | map(attribute='volumes') 
        | flatten 

        | map('split', ':') 
        | map('first') 
        | unique 

        | map('community.general.dict_kv', 'path') 
        | list
      }}

- name: Debug
  ansible.builtin.debug:
    msg:
      - "{{ pdmn_webssh2_dirs }}"

- name: Create dirs
  ansible.builtin.file:
    state: directory
    owner: "{{ pdmn_webssh2_item.owner | default(pdmn_webssh2_default_owner) }}"
    group: "{{ pdmn_webssh2_item.group | default(pdmn_webssh2_default_group) }}"
    mode: "{{ pdmn_webssh2_item.mode | default(pdmn_webssh2_default_dir_mode) }}"
    path: "{{ pdmn_webssh2_item.path }}"
  loop: "{{ pdmn_webssh2_dirs }}"
  loop_control:
    loop_var: pdmn_webssh2_item
    label: "{{ pdmn_webssh2_item.path }}"

- name: Pull images
  containers.podman.podman_image:
    name: "{{ pdmn_webssh2_item.image }}:{{ pdmn_webssh2_item.release }}"
    state: present
  loop: "{{ pdmn_webssh2_containers }}"
  loop_control:
    loop_var: pdmn_webssh2_item
    label: "{{ pdmn_webssh2_item.name }}"
  ignore_errors: true

- name: config.json
  ansible.builtin.copy:
    owner: 1000
    group: 1000
    mode: '0600'
    dest: "{{ pdmn_webssh2_pod_dir }}/config.json"
    content: "{{ pdmn_webssh2_config | to_nice_json }}"

- name: Create pod
  containers.podman.podman_pod:
    state: created
    name: "{{ pdmn_webssh2_podname }}"
    publish: "{{ pdmn_webssh2_publish }}"

- name: Run containers
  containers.podman.podman_container:
    state: started
    privileged: true
    pod: "{{ pdmn_webssh2_item.pod }}"
    name: "{{ pdmn_webssh2_item.name }}"
    image: "{{ pdmn_webssh2_item.image }}:{{ pdmn_webssh2_item.release }}"
    env: "{{ pdmn_webssh2_item.env | default({}) }}"
    restart_policy: "{{ pdmn_webssh2_item.restart | default('always') }}"
    requires: "{{ pdmn_webssh2_item.requires | default([]) }}"
    volume: "{{ (pdmn_webssh2_item.volumes | default([]) + pdmn_webssh2_item.files | default([])) }}"
    healthcheck: "{{ (pdmn_webssh2_item.healthcheck.test | default([]))[1] | default(omit) }}"
    healthcheck_interval: "{{ (pdmn_webssh2_item.healthcheck | default({})).interval | default(omit) }}"
    healthcheck_timeout: "{{ (pdmn_webssh2_item.healthcheck | default({})).timeout | default(omit) }}"
    healthcheck_retries: "{{ (pdmn_webssh2_item.healthcheck | default({})).retries | default(omit) }}"
  loop: "{{ pdmn_webssh2_containers }}"
  loop_control:
    loop_var: pdmn_webssh2_item
    label: "{{ pdmn_webssh2_item.name }}"
  ignore_errors: true

# - name: Create systemd directory for user if rootless
#   ansible.builtin.file:
#     path: "~/.config/systemd/user"
#     state: directory
#     mode: '0755'
#   # Раскомментируйте строку ниже, если запускаете контейнеры НЕ от root
#   # when: ansible_user_id != 'root'

# - name: Generate systemd unit files for pod and containers
#   ansible.builtin.command:
#     cmd: "podman generate systemd --new --files --name {{ pdmn_webssh2_podname }}"
#     chdir: "{{ (ansible_user_id == 'root') | ternary('/etc/systemd/system', '~/.config/systemd/user') }}"
#   changed_when: true

- name: Generate systemd unit files
  containers.podman.podman_generate_systemd:
    new: false
    no_header: false
    restart_policy: always
    restart_sec: 60
    use_names: true
    dest: "{{ pdmn_webssh2_systemd_dir }}"
    force: "{{ pdmn_webssh2_force }}"
    name: "{{ pdmn_webssh2_podname }}"
  notify: restart guacamole

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: "{{ (ansible_user_id == 'root') | ternary('system', 'user') }}"

- name: Enable and start pod service
  ansible.builtin.systemd_service:
    name: "pod-{{ pdmn_webssh2_podname }}.service"
    enabled: true
    state: started
    scope: "{{ (ansible_user_id == 'root') | ternary('system', 'user') }}"

- name: Enable linger for rootless user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ ansible_user_id }}"
  changed_when: false
  when: ansible_user_id != 'root'
